// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urcsykcojsffnzjcmdwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyY3N5a2NvanNmZm56amNtZHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTQ2MTgsImV4cCI6MjA2Mzk5MDYxOH0.VtpnS0j6GyzDy5yGEzVe1ut4NChm4mpkMR_tVo8pvDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);